name       : mate-common
version    : 1.20.0
release    : 3
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-common-1.20.0.tar.xz : 616d9c319ee892f05494570fb0f7316c10f17a1f8d15d0a9a6ae38c320161a41
license    : GPL-3.0
component  : programming.tools
summary    : Tools to build MATE from git
patterns   :
    - /*
description: |
    Tools to build MATE from git
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
