name       : mate-common
version    : 1.24.0
release    : 5
source     :
    - https://github.com/mate-desktop/mate-common/archive/v1.24.0.tar.gz : bec14644185356badeb8076ffbcb32ff3a81e3613645793fe70598f69b5a9fe8
license    : GPL-3.0-or-later
component  : programming.tools
summary    : Tools to build MATE from git
description: |
    Common scripts and macros to develop with MATE
patterns   :
    - /*
rundeps    :
    - autoconf-archive
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
