name       : mate-common
version    : 1.24.2
release    : 6
source     :
    - https://github.com/mate-desktop/mate-common/archive/v1.24.2.tar.gz : 006be3d6b105fc5c74e79524099172768f7ac983ab111e711858e3f63d01d3a4
license    : GPL-3.0-or-later
component  : programming.tools
summary    : Tools to build MATE from git
description: |
    Common scripts and macros to develop with MATE
patterns   :
    - /*
rundeps    :
    - autoconf-archive
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
