name       : mate-common
version    : 1.27.0
release    : 8
source     :
    - https://github.com/mate-desktop/mate-common/releases/download/v1.27.0/mate-common-1.27.0.tar.xz : 7008912b580f2f19f75ae74ffad728ce5cf23d1f8c1ca3cc4adcd5f7a922d18e
license    : GPL-3.0-or-later
component  : programming.tools
summary    : Tools to build MATE from git
description: |
    Common scripts and macros to develop with MATE
patterns   :
    - /*
rundeps    :
    - autoconf-archive
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
