name       : mate-common
version    : 1.18.0
release    : 2
source     :
    - https://pub.mate-desktop.org/releases/1.18/mate-common-1.18.0.tar.xz : d77c44546e748f94cf93707ab3593146109401c9bcde533fc308863f9ca20580
license    : GPL-3.0
component  : programming.tools
summary    : Tools to build MATE from git
patterns   :
    - /*
description: |
    Tools to build MATE from git
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
