name       : mate-common
version    : 1.16.0
release    : 1
source     :
    - http://pub.mate-desktop.org/releases/1.16/mate-common-1.16.0.tar.xz : 34d3a8c58647806aebde24f705c07e1dc8083cd4baa55b45d3e51e367c2ef20a
license    : GPL-3.0
component  : programming.tools
summary    : Tools to build MATE from git
patterns   :
    - /*
description: |
    Tools to build MATE from git
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
