name       : mate-common
version    : 1.22.0
release    : 4
source     :
    - https://github.com/mate-desktop/mate-common/archive/v1.22.0.tar.gz : 0500caab4074718461222db7c3cafa90f7331012c02c77d42a84ecd7f5bc0620
license    : GPL-3.0-or-later
component  : programming.tools
summary    : Tools to build MATE from git
patterns   :
    - /*
description: |
    Common scripts and macros to develop with MATE
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
